config/routes.rb
Rails.application.routes.draw do
  devise_for:customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }
  scope module: :customers do
    root to:'homes#top'
    get '/about' => 'homes#about'
    resources :items, only:[:index,:show]
    patch 'customers/withdraw' => 'customers#withdraw'
    resources :customers, only:[:edit,:update]
    get 'customers/unsubscribe' => 'customers#unsubscribe', as:'customers_unsubscribe'
    get '/customers/my_page' => 'customers#show'
    resources :addresses, only:[:index,:edit,:create,:update,:destroy]
    delete '/cart_items/all_destroy' => 'cart_items#all_destroy', as:'cart_items_all_destroy'
    resources :cart_items, only:[:index,:update,:create,:destroy]
    #post '/orders/new' => 'orders#new'
    post '/orders/confirm' => 'orders#confirm'
    get '/orders/complete' => 'orders#complete'
    resources :orders, only:[:index,:create,:new,:show]

  end

  devise_for(
    :admins,
    path: 'admin',
    module: 'devise'
    )

    namespace :admin do
      root to:'homes#top'
      patch '/items/:id' => 'items#update', as:'update_items'
      resources :items, only:[:index,:new,:show,:edit,:create]
      resources :genres, only:[:index,:create,:edit,:update]
      resources :customers, only:[:index,:edit,:show]
      patch '/customers/:id' => 'customers#update', as:'update_customers'
      resources :orders, only:[:show,:update]
      resources :order_details, only:[:show,:update]
    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders

  has_many :addresses

  has_many :cart_items

  #退会機能
  def active_for_authentication?
    super && (self.is_deleted == false)
  end

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy

  belongs_to :customer

  enum payment_method: {クレジットカード: 0, 銀行振込:1 }
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
before_action :authenticate_admin!,only: [:show,:edit,:update]
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    customer = Customer.find(params[:id])
    customer.update(customer_params)
    redirect_to admin_customers_path
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:telephone_number,:email,:is_deleted)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
before_action :authenticate_admin!
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

end

app/controllers/customers/addresses_controller.rb
class Customers::AddressesController < ApplicationController
before_action :authenticate_customer!

  def index
    @address = Address.new
    @addresses = current_customer.addresses
  end

  def create
    @address = Address.new(address_params)
    @address.customer_id = current_customer.id
    if @address.save
      redirect_to addresses_path
    else
      render 'index'
      @address = Address.new
      @addresses = Address.all
    end
  end

  def edit
    @address = Address.find(params[:id])
  end
  def update
    address = Address.find(params[:id])
    address.update(address_params)
    redirect_to addresses_path
  end

  def destroy
    address = Address.find(params[:id])
    address.destroy
    redirect_to addresses_path
  end

  private
  def address_params
    params.require(:address).permit(:name,:postal_code,:address,:customer_id)
  end


end

app/controllers/customers/cart_items_controller.rb
class Customers::CartItemsController < ApplicationController
before_action :authenticate_customer!
    def index
        @cart_items = current_customer.cart_items
    end



    def create
        @cart_item = CartItem.new(cart_item_params)
        if @cart_item.save
            redirect_to cart_items_path
        else
            render "customers/items/show"
        end
    end

    def update
        @cart_item = CartItem.find(params[:id])
        @cart_item .update(cart_item_params)
        redirect_to cart_items_path
    end

    def destroy
        cart_item = CartItem.find(params[:id])
        cart_item.destroy
        redirect_to cart_items_path
    end

    def all_destroy
        cart_item = current_customer.cart_items
        cart_item.destroy_all
        redirect_to cart_items_path
    end

    private
    def cart_item_params
        params.require(:cart_item).permit(:amount,:item_id,:customer_id)
    end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/customers_controller.rb
class Customers::CustomersController < ApplicationController
before_action :authenticate_customer!

  def show
    @customer = current_customer
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = current_customer
    @customer.update(customer_params)
    redirect_to customers_my_page_path
  end

  def withdraw
    @customer = current_customer
    @customer.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end



  private
  def customer_params
    params.require(:customer).permit(:last_name,:first_name,:last_name_kana,:first_name_kana,:email,:postal_code,:address,:telephone_number,:is_deleted)
  end


end

app/controllers/customers/homes_controller.rb
class Customers::HomesController < ApplicationController
end

app/controllers/customers/items_controller.rb
class Customers::ItemsController < ApplicationController
before_action :authenticate_customer!,only: [:show]
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end

end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController
before_action :authenticate_customer!
  def new
    @order = Order.new
  end

  def confirm
    #binding.pry
    @order = Order.new(order_params)
    #@address = Address.find(params[:order][:address_id])
    @cart_items = current_customer.cart_items
    if params[:address_option] == "0"
      @order.address = current_customer.address
      @order.name = current_customer.last_name + current_customer.first_name
      @order.postal_code = current_customer.postal_code
    elsif params[:address_option] == "1"
      @address = Address.find(params[:address_id])
      @order.address = @address.address
      @order.name = @address.name
      @order.postal_code = @address.postal_code
    end
  end

  def create
    #オーダー（郵便番号・住所・名前・請求金額・支払方法andユーザーID・送料）
    @order = Order.new(order_params)
    @order.customer_id = current_customer.id
    @order.shipping_cost = 800
    @order.save
    #商品１つずつcreate(オーダーID・アイテムID・税込金額・個数)
    @cart_items = current_customer.cart_items.all
  @cart_items.each do |cart_item|
    @order_detail = OrderDetail.new
    @order_detail.order_id = @order.id
    @order_detail.item_id = cart_item.item.id
    @order_detail.price = cart_item.item.with_tax_price
    @order_detail.amount = cart_item.amount
    @order_detail.save
  end
    #カート内商品を全部削除（defじゃないからルーティング不要）
    @cart_items.destroy_all
    redirect_to orders_complete_path
  end

  def index
    @orders = current_customer.orders
  end

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  private
  def order_params
    params.require(:order).permit(:payment_method,:name,:address,:postal_code,:total_payment)
  end

end

#

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/customers/addresses_helper.rb
module Customers::AddressesHelper
end

app/helpers/customers/cart_items_helper.rb
module Customers::CartItemsHelper
end

app/views/customers/orders/complete.html.erb
<h1>注文完了</h1>
<h5>ご注文ありがとうございました！</h5>

app/views/customers/orders/confirm.html.erb
<h1>注文情報確認画面</h1>


<% @sum = 0 %>


<table  border="1" class="item-table">
    <tr class="item-table-title">
        <th>商品名</th>
        <th>税込価格</th>
        <th>個数</th>
        <th>商品小計</th>
    </tr>
<% @cart_items.each do |cart_item| %>
<tr>
    <th><%=cart_item.item.name %></th>
    <th><%=cart_item.item.with_tax_price %></th>
    <th><%=cart_item.amount %>個</th>
    <th><%=cart_item.subtotal %>円</th>
    <% @sum += cart_item.subtotal %>
</tr>
<% end %>
</table>



<table border="1" class="order-payment_method">
    <tr>
        <th class="order-total">送料</th>
        <td><%= 800 %>円</td>
    </tr>
    <tr>
        <th>商品合計</th>
        <td><%= @sum %>円</td>
    </tr>
    <tr>
        <th>請求金額</th>
        <td><%= @sum + 800 %>円</td>
    </tr>
</table>


<div class="order-pay-detail">
    <h4>支払い方法</h4>
    <p><%=@order.payment_method %></p>

    <h4>お届け先</h4>
    <p>〒<%= @order.postal_code %> <%= @order.address %></p>
    <p><%= @order.name %></p>
</div>
<div class="order-button">
<%=form_with model:@order, url: orders_path, local:true do |f| %>
<%=f.hidden_field :postal_code, value: @order.postal_code %>
<%=f.hidden_field :address, value: @order.address %>
<%=f.hidden_field :name, value: @order.name %>
<%=f.hidden_field :total_payment, value: (@sum + 800) %>
<%=f.hidden_field :payment_method, value: @order.payment_method %>
<%=f.submit"注文を確定する" %>
<% end %>
</div>

app/views/customers/orders/index.html.erb
<h1>注文履歴</h1>

<table border="1" class="item-table">
    <tr class="item-table-title">
        <th>注文日</th>
        <th>配送先</th>
        <th>注文商品</th>
        <th>支払金額</th>
        <th>注文詳細</th>
    </tr>
    <% @orders.each do |order| %>
    <tr>
        <td><%=order.created_at.strftime('%y/%m/%d') %></td>
        <td><%=order.postal_code %><%=order.address %></td>
        <td><% order.order_details.each do |order_detail| %>
            <%=order_detail.item.name %><br>
            <% end %>
        </td>
        <td><%=order.total_payment %>円</td>
        <td><%=link_to "詳細へ",order_path(order.id)%></td>
    </tr>
    <% end %>
</table>

app/views/customers/orders/new.html.erb
<h1>注文情報入力画面</h1>

<div class="order">
    <div>
        <p>支払方法</p>
        <div class="order-content">
            <%=form_with model:@order, url:orders_confirm_path, local:true do |f| %>
            <%= f.radio_button :payment_method, "クレジットカード" %>
            <%= f.label :payment_method, "クレジットカード" %>

            <%= f.radio_button :payment_method, "銀行振込" %>
            <%= f.label :payment_method, "銀行振込" %>
        </div>
    </div>

    <div>
    <p>お届け先</p>
    <div class="order-content">
        <%= radio_button_tag :address_option, 0 ,{:checked => true} %>
        <%=f.label :address,"ご自身の住所" %>
        <%= "#{current_customer.postal_code} #{current_customer.address}" %>
        <%= "#{current_customer.last_name} #{current_customer.first_name}" %></br>

        <%= radio_button_tag :address_option, 1 %>
        <%=f.label :address, "登録済み住所から選択"%>
        <%= select_tag :address_id, options_from_collection_for_select(Address.all, :id, :full_address) %><br>

        <%= radio_button_tag :address_option, 2 %>
        <%=f.label :address, "新しいお届け先" %></br>
        <div class="order-content-new">
            <p>郵便番号　　<%=f.text_field :postal_code %></p>
            <p>住所　　　　<%=f.text_field :address %></p>
            <p>宛名　　　　<%=f.text_field :name %></p>
        </div>
    </div>
    <div class="order-button">
        <%=f.submit"確認画面へ進む"%>
    </div>
        <% end %>
    </div>
</div>

app/views/customers/orders/show.html.erb
<h1>注文履歴詳細画面</h1>

<div class="order-detail">
  <div class="order">
    <div>
      <h4>注文情報</h4>
      <table border="1">
        <tr>
          <th>注文日</th>
          <td><%=@order.created_at.strftime('%y/%m/%d') %></td>
        </tr>
        <tr>
          <th>配送先</th>
          <td>
            〒<%=@order.postal_code %><br>
            <%=@order.address %><br>
            <%=@order.name %><br>
          </td>
        </tr>
        <tr>
          <th>支払方法</th>
          <td><%=@order.payment_method %></td>
        </tr>
      </table>
    </div>
  </div>

  <div class="order-pay">
    <h4>請求情報</h4>
    <table border="1" class="order-table">
      <tr>
        <th>商品合計</th>
        <td><%=@order.total_payment - 800 %></td>
      </tr>
      <tr>
        <th>配送料</th>
        <td><%=@order.shipping_cost %></td>
      </tr>
      <tr>
        <th>ご請求額</th>
        <td><%=@order.total_payment %></td>
      </tr>
    </table>
  </div>
</div>


<div class="order-content">
  <h4>注文内容</h4>
  <table border="1">
    <tr>
      <th>商品</th>
      <th>単価（税込）</th>
      <th>個数</th>
      <th>小計</th>
    </tr>
  <% @order_details.each do |order_detail| %>
  <tr>
      <th><%=order_detail.item.name %></th>
      <th><%=order_detail.price %></th>
      <th><%=order_detail.amount %>個</th>
      <th><%=(order_detail.price).floor * (order_detail.amount)%>円</th>
  </tr>
  <% end %>

  </table>
</div>